### ISSUE TITLE
Imitation Learning of Agenda-Based Semantic Parsers (TACL 2015)

### ISSUE THREAD

**Issue by hjw9673** [percyliang/sempre#108]
How can I re-construct the experiment done in the paper(Imitation Learning of Agenda-Based Semantic Parsers (TACL 2015))?

Is it ./run @mode=freebase?

+) Do I need to download any dependencies or source code?

**Comment by percyliang** [comment]
You can find the reproducible experiments on CodaLab:
https://worksheets.codalab.org/worksheets/0x8fdfad310dd84b7baf683b520b4b64d5/

**Comment by hjw9673** [comment]
when I execute the following command, 

./run @mode=freebase @domain=webquestions @sparqlserver=jonsson:3093 @cacheserver=local @train=1 @agenda=1 @data=1 @entitysearch=1 @pooldir=0 -EntityLexicon.mid2idPath canonical-id-map -FreebaseTypeLookup.entityTypesPath canonicalized.en-types -FreebaseSearch.cachePath cache-files/freebase_search.cache -SparqlExecutor.cachePath cache-files/sparql.cache -Lexicon.cachePath cache-files/lexicon.cache -Builder.parser BeamParser -Parser.coarsePrune -stdout false

I get this error.

java.lang.RuntimeException: java.net.UnknownHostException: jonsson
	at edu.stanford.nlp.sempre.freebase.SparqlExecutor.makeRequest(SparqlExecutor.java:136)
	at edu.stanford.nlp.sempre.freebase.SparqlExecutor.runQueryToGetXml(SparqlExecutor.java:196)
	at edu.stanford.nlp.sempre.freebase.SparqlExecutor.execute(SparqlExecutor.java:250)
	at edu.stanford.nlp.sempre.freebase.SparqlExecutor.execute(SparqlExecutor.java:233)
	at edu.stanford.nlp.sempre.Derivation.ensureExecuted(Derivation.java:261)
	at edu.stanford.nlp.sempre.FeatureExtractor.extractDenotationFeatures(FeatureExtractor.java:98)
	at edu.stanford.nlp.sempre.FeatureExtractor.extractLocal(FeatureExtractor.java:65)
	at edu.stanford.nlp.sempre.ParserState.featurizeAndScoreDerivation(ParserState.java:77)
	at edu.stanford.nlp.sempre.BeamParserState.applyRule(BeamParser.java:147)
	at edu.stanford.nlp.sempre.BeamParserState.applyCatUnaryRules(BeamParser.java:193)
	at edu.stanford.nlp.sempre.BeamParserState.build(BeamParser.java:126)
	at edu.stanford.nlp.sempre.BeamParserState.infer(BeamParser.java:98)
	at edu.stanford.nlp.sempre.Parser.parse(Parser.java:159)
	at edu.stanford.nlp.sempre.Learner.parseExample(Learner.java:252)
	at edu.stanford.nlp.sempre.Learner.processExamples(Learner.java:169)
	at edu.stanford.nlp.sempre.Learner.learn(Learner.java:111)
	at edu.stanford.nlp.sempre.Learner.learn(Learner.java:82)
	at edu.stanford.nlp.sempre.Main.run(Main.java:23)
	at fig.exec.Execution.runWithObjArray(Execution.java:337)
	at fig.exec.Execution.run(Execution.java:325)
	at edu.stanford.nlp.sempre.Main.main(Main.java:38)
Caused by: java.net.UnknownHostException: jonsson
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at edu.stanford.nlp.sempre.freebase.SparqlExecutor.makeRequest(SparqlExecutor.java:110)
	... 20 more
4 errors, 0 warnings
Command failed: java -ea -Dmodules=core,freebase -Xms8G -Xmx10G -cp libsempre/*:lib/* edu.stanford.nlp.sempre.Main -execDir exec -overwriteExecDir -addToView 0 -SparqlExecutor.endpointUrl http://jonsson:3093/sparql -FeatureExtractor.featureDomains basicStats alignmentScores entityFeatures context skipPos joinPos wordSim lexAlign tokenMatch rule opCount constant denotation whType span derivRank lemmaAndBinaries -Builder.executor freebase.SparqlExecutor -Builder.valueEvaluator freebase.FreebaseValueEvaluator -LanguageAnalyzer.languageAnalyzer corenlp.CoreNLPAnalyzer -LexiconFn.lexiconClassName edu.stanford.nlp.sempre.fbalignment.lexicons.Lexicon -BinaryLexicon.binaryLexiconFilesPath lib/fb_data/7/binaryInfoStringAndAlignment.txt -BinaryLexicon.keyToSortBy Intersection_size_typed -UnaryLexicon.unaryLexiconFilePath lib/fb_data/7/unaryInfoStringAndAlignment.txt -EntityLexicon.entityPopularityPath lib/fb_data/7/entityPopularity.txt -TypeInference.typeLookup freebase.FreebaseTypeLookup -FreebaseSearch.cachePath /u/nlp/data/semparse/scr/cache/fbsearch/1.cache -Dataset.inPaths train,lib/data/webquestions/dataset_11/webquestions.examples.train.json test,lib/data/webquestions/dataset_11/webquestions.examples.test.json -Grammar.inPaths freebase/data/emnlp2013.grammar -Parser.beamSize 200 -Lexicon.cachePath LexiconFn.cache -SparqlExecutor.cachePath SparqlExecutor.cache -FreebaseSearch.cachePath FreebaseSearch.cache -EntityLexicon.inexactMatchIndex lib/lucene/4.4/inexact/ -LexiconFn.maxEntityEntries 10 -Grammar.tags webquestions bridge join inject inexact -Learner.maxTrainIters 3 -BridgeFn.useBinaryPredicateFeatures true -BridgeFn.filterBadDomain true -Dataset.splitRandom 1 -EntityLexicon.mid2idPath canonical-id-map -FreebaseTypeLookup.entityTypesPath canonicalized.en-types -FreebaseSearch.cachePath cache-files/freebase_search.cache -SparqlExecutor.cachePath cache-files/sparql.cache -Lexicon.cachePath cache-files/lexicon.cache -Builder.parser BeamParser -Parser.coarsePrune -stdout false

Possible solution? 
Thank you.

**Comment by yonatansito** [comment]
You are trying to run the FixedOrder (beam parsing) experiment and not the agenda parser (AgendaIL), is that right?
Does the AgendaIL experiment work, i.e., just delete from your command line:
`-Builder.parser BeamParser -Parser.coarsePrune`
?

If so, then it is most likely that the reason is this:
The parser needs to call a sparql server to get the result of the execution of logical forms.
To avoid having to call the server I put the results of all executions in the cache file cache-files/sparql.cache. But perhaps the cache contains only entries for AgendaIL and not FixedOrder (I don't remember), and then when you run the beam parser it tries to connect to a sparql server that doesn't exist.

There are several possible solutions for that:
a) You create your own sparql server over Freebase and change the option to
`@sparqlserver=<your_server>`
b) I add cache files for that parser as well. I can do that, but it might take some time.
c) We set up a public server for you. From what I remember in the past that was quite slow - about 6 seconds per example, so I am not sure if it's worth it. 

If AgendaIL also doesn't work then I will need to re-produce this and it'd be great if you send the full log file.

**Comment by hjw9673** [comment]
The AgendaIL doesn't work for me too.

I would really appreciate if you can set up a public server for me and what
do you mean by full log file?

Thank you.

**Comment by yonatansito** [comment]
Hi,
I downloaded all the code and data from 
https://worksheets.codalab.org/worksheets/0x8fdfad310dd84b7baf683b520b4b64d5/

and then ran the AgendaIL command and it works as expected, so I am unable to re-produce the error. I am not sending any requests to the sparql server, everything is in the provided cache files.
Did you download everything from the codalab worksheet (i.e. not using git clone etc.)?

If I can not reproduce the error I can not really do much...

What is your use case? 
If you just want to replicate the results, this should work.
But if you plan to actively change the code, there is no alternative and you will have to have your own sparql server instance, since at some point you will need a query that is not in the cache files

**Comment by hjw9673** [comment]
I believe I downloaded everything from the codalab worksheet. (Is there a
way to download every file at once or do I have to download all the files
one by one?)

For now, I just would like to replicate the result.

But for the future, I would like to observe the result with use my own
dataset.

Thank you.

**Comment by yonatansito** [comment]
As I said, when I just downloaded all the files one by one and did exactly as instructed it worked.
If you did that as well and it did not work then it is hard for me to say what the problem is.

But if you plan to do anything yourself in the future over Freebase, you will need an executor, which means you will have to install your own sparql instance and upload freebase to it.

**Comment by zjjj** [comment]
I also met a similar problem. I downloaded every single file from [https://worksheets.codalab.org/worksheets/0x8fdfad310dd84b7baf683b520b4b64d5/](https://worksheets.codalab.org/worksheets/0x8fdfad310dd84b7baf683b520b4b64d5/)

I even tried to recompile the source code with the following command successfully:
<code>
$ ant freebase corenlp
</code>

But when I used the AgendaIL command from the webpage:
<code>
$ ./run @mode=freebase @domain=webquestions @sparqlserver=jonsson:3093 @cacheserver=local @train=1 @agenda=1 @data=1 @entitysearch=1 @pooldir=0 -EntityLexicon.mid2idPath canonical-id-map -FreebaseTypeLookup.entityTypesPath canonicalized.en-types -FreebaseSearch.cachePath cache-files/freebase_search.cache -SparqlExecutor.cachePath cache-files/sparql.cache -Lexicon.cachePath cache-files/lexicon.cache -stdout false
</code>

I got this error:
<code>
2 errors, 0 warnings
Command failed: java -ea -Dmodules=core,freebase -Xms8G -Xmx10G -cp libsempre/*:lib/* edu.stanford.nlp.sempre.Main -execDir exec -overwriteExecDir -addToView 0 -SparqlExecutor.endpointUrl http://jonsson:3093/sparql -FeatureExtractor.featureDomains basicStats alignmentScores entityFeatures context skipPos joinPos wordSim lexAlign tokenMatch rule opCount constant denotation whType span derivRank lemmaAndBinaries -Builder.executor freebase.SparqlExecutor -Builder.valueEvaluator freebase.FreebaseValueEvaluator -LanguageAnalyzer.languageAnalyzer corenlp.CoreNLPAnalyzer -LexiconFn.lexiconClassName edu.stanford.nlp.sempre.fbalignment.lexicons.Lexicon -BinaryLexicon.binaryLexiconFilesPath lib/fb_data/7/binaryInfoStringAndAlignment.txt -BinaryLexicon.keyToSortBy Intersection_size_typed -UnaryLexicon.unaryLexiconFilePath lib/fb_data/7/unaryInfoStringAndAlignment.txt -EntityLexicon.entityPopularityPath lib/fb_data/7/entityPopularity.txt -TypeInference.typeLookup freebase.FreebaseTypeLookup -FreebaseSearch.cachePath /u/nlp/data/semparse/scr/cache/fbsearch/1.cache -Dataset.inPaths train,lib/data/webquestions/dataset_11/webquestions.examples.train.json test,lib/data/webquestions/dataset_11/webquestions.examples.test.json -Grammar.inPaths freebase/data/emnlp2013.grammar -Parser.beamSize 200 -Lexicon.cachePath LexiconFn.cache -SparqlExecutor.cachePath SparqlExecutor.cache -FreebaseSearch.cachePath FreebaseSearch.cache -Grammar.tags webquestions bridge join inject fbsearch0 -LexiconFn.maxEntityEntries 10 -Learner.maxTrainIters 3 -BridgeFn.useBinaryPredicateFeatures true -BridgeFn.filterBadDomain true -Dataset.splitRandom 1 -SparqlExecutor.lambdaAllowDiagonals false -Builder.parser ReinforcementParser -LexiconFn.maxEntityEntries 20 -Dataset.splitRandom 1 -ReinforcementParser.lowProb 0.01 -Parser.beamSize 200 -Params.l1Reg lazy -Params.l1RegCoeff 1.0e-05 -EntityLexicon.mid2idPath canonical-id-map -FreebaseTypeLookup.entityTypesPath canonicalized.en-types -FreebaseSearch.cachePath cache-files/freebase_search.cache -SparqlExecutor.cachePath cache-files/sparql.cache -Lexicon.cachePath cache-files/lexicon.cache -stdout false
</code>

Any ideas how to make it work? Thanks.

**Comment by umas** [comment]
Hi Zjjj, you may have untarred the files wrong (that is what happened with me). The files uploaded to codalab worksheet are supposed to be in their own specific directories. When you untar them into the main directory, it leads to a path error. The exact error appears in a log file. Perhaps exec/log? I don't remember the name. But you can find it by doing ls -ltr.

**Comment by zjjj** [comment]
Hi @umas , that solves the problem, thanks a million!
After the program finished running, it reports 114 errors and 4 warnings, but it seems that the outputs has been written into exec/log. So shall I trust the results?

**Comment by umas** [comment]
The stderr file uploaded in codalab also reports 114 errors and 4 warnings.
So I suppose we have got it right. You can cross check the f1 numbers you
have got with those uploaded on codalab.

**Comment by zjjj** [comment]
I see. Thanks again.
