### ISSUE TITLE
Cannot work on simple-freebase mode

### ISSUE THREAD

**Issue by zhaopku** [percyliang/sempre#119]
I have installed `sempre` and `virtuoso`, and I have successfully go through the **Setting up your own Virtuoso graph database** section. (However, I skipped the **Setting up a copy of Freebase** section). I have problems when I try the first example in the **lambda DCS** section. After starting the virtuoso database successfully (`freebase/scripts/virtuoso start tutorial.vdb 3001`), I tried this command:

`./run @mode=simple-freebase @sparqlserver=localhost:3001`

Then I have error messages like this:
```
main() {
  Grammar.read {
    Lexicon() {
      Loading unary lexicon file /dev/null {
        Number of lexemes: 0
      }
      Loading Freebase schema: lib/fb_data/93.exec/schema2.ttl {
        1163 CVTs, (19337,19282) property types, 858 property units
      }
      Loading formula info... {
        Adding schema properties
        Current number of binary formulas: 19278
        Current number of unary formulas: 19284
        Compuing reverse for schema formulas
        Adding reverse formulas: 19278
        Current number of binary formulas: 38556
        Generate formulas through CVTs
        Current number of binary formulas: 57226
      } [1.2s, cum. 1.9s]
      Loading binary lexicon file /dev/null {
        Number of entries: 0
      }
    } [1.9s, cum. 1.9s]
    RemoteStringCache: connecting to freebase.cloudapp.net:4000 to access freebase-rdf-2013-06-09-00-00.canonicalized.en-types.gz 
java.lang.RuntimeException: java.net.UnknownHostException: freebase.cloudapp.net
	at edu.stanford.nlp.sempre.cache.RemoteStringCache.<init>(RemoteStringCache.java:37)
	at edu.stanford.nlp.sempre.cache.StringCacheUtils.create(StringCacheUtils.java:15)
	at edu.stanford.nlp.sempre.freebase.FreebaseTypeLookup.getEntityTypes(FreebaseTypeLookup.java:28)
	at edu.stanford.nlp.sempre.freebase.FreebaseTypeLookup.getEntityType(FreebaseTypeLookup.java:41)
	at edu.stanford.nlp.sempre.TypeInference.inferType(TypeInference.java:143)
	at edu.stanford.nlp.sempre.TypeInference.inferType(TypeInference.java:177)
	at edu.stanford.nlp.sempre.TypeInference.inferType(TypeInference.java:112)
	at edu.stanford.nlp.sempre.TypeInference.inferType(TypeInference.java:106)
	at edu.stanford.nlp.sempre.ConstantFn.init(ConstantFn.java:26)
	at edu.stanford.nlp.sempre.Grammar.parseSemanticFn(Grammar.java:471)
	at edu.stanford.nlp.sempre.Grammar.interpretRule(Grammar.java:255)
	at edu.stanford.nlp.sempre.Grammar.interpret(Grammar.java:154)
	at edu.stanford.nlp.sempre.Grammar.readOnePath(Grammar.java:130)
	at edu.stanford.nlp.sempre.Grammar.read(Grammar.java:61)
	at edu.stanford.nlp.sempre.Grammar.read(Grammar.java:53)
	at edu.stanford.nlp.sempre.Builder.buildUnspecified(Builder.java:45)
	at edu.stanford.nlp.sempre.Builder.build(Builder.java:38)
	at edu.stanford.nlp.sempre.Main.run(Main.java:17)
	at fig.exec.Execution.runWithObjArray(Execution.java:337)
	at fig.exec.Execution.run(Execution.java:325)
	at edu.stanford.nlp.sempre.Main.main(Main.java:38)
Caused by: java.net.UnknownHostException: freebase.cloudapp.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at edu.stanford.nlp.sempre.cache.RemoteStringCache.<init>(RemoteStringCache.java:26)
	... 20 more
    ERROR: java.lang.RuntimeException: Error on (rule $NP (actors) (ConstantFn (fb:people.person.profession fb:en.film_actor))): java.lang.RuntimeException: java.net.UnknownHostException: freebase.cloudapp.net:
edu.stanford.nlp.sempre.Grammar.interpret(Grammar.java:176)
edu.stanford.nlp.sempre.Grammar.readOnePath(Grammar.java:130)
edu.stanford.nlp.sempre.Grammar.read(Grammar.java:61)
edu.stanford.nlp.sempre.Grammar.read(Grammar.java:53)
edu.stanford.nlp.sempre.Builder.buildUnspecified(Builder.java:45)
edu.stanford.nlp.sempre.Builder.build(Builder.java:38)
edu.stanford.nlp.sempre.Main.run(Main.java:17)
fig.exec.Execution.runWithObjArray(Execution.java:337)
fig.exec.Execution.run(Execution.java:325)
edu.stanford.nlp.sempre.Main.main(Main.java:38)
1 errors, 0 warnings
  } [2.0s, cum. 2.1s]
Command failed: java -Dmodules=core,freebase -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -executor freebase.SparqlExecutor -SparqlExecutor.endpointUrl http://localhost:3001/sparql -FreebaseSearch.cachePath FreebaseSearch.cache -EntityLexicon.mid2idPath freebase.cloudapp.net:4000:freebase-rdf-2013-06-09-00-00.canonical-id-map.gz -TypeInference.typeLookup freebase.FreebaseTypeLookup -FreebaseTypeLookup.entityTypesPath freebase.cloudapp.net:4000:freebase-rdf-2013-06-09-00-00.canonicalized.en-types.gz -EntityLexicon.maxEntries 2 -FeatureExtractor.featureDomains rule -Parser.coarsePrune -JoinFn.typeInference -UnaryLexicon.unaryLexiconFilePath /dev/null -BinaryLexicon.binaryLexiconFilesPath /dev/null -Grammar.inPaths freebase/data/demo1.grammar -SparqlExecutor.returnTable -Main.interactive

```
which should start a command prompt according to the **tutorial**.
Any suggestions to fix this?

**Comment by robinsonOdhiambo** [comment]
Freebase has been deprecated by google so the server is not accecible use this commands to set up a local cache server : ./run @mode=simple-freebase @sparqlserver=localhost:3001 @cacheserver=localhost:4000

and then excute this command to start sempre's interractive shell
 ./run @mode=simple-freebase @sparqlserver=localhost:3001 @cacheserver=localhost:4000

**Comment by zhaopku** [comment]
@robinsonOdhiambo Sorry, but is the command to set up a local cache server the same as the command to start the interactive shell?

**Comment by robinsonOdhiambo** [comment]
@zhaopku sorry my mistake to start the local cache server use :
 ./run @mode=cacheserver -readOnly -capacity MAX -basePath lib/fb_data
