### ISSUE TITLE
ArrayIndexOutOfBoundsException with FloatingParser

### ISSUE THREAD

**Issue by azimuthny** [percyliang/sempre#143]
I am running into the following error:

> add 1 to 3
  Parser.parse: parse {
    FloatingParser.infer()Exception in thread "Thread-2" java.lang.ArrayIndexOutOfBoundsException: -1
        at java.util.ArrayList.elementData(ArrayList.java:418)
        at java.util.ArrayList.get(ArrayList.java:431)
        at edu.stanford.nlp.sempre.LanguageInfo.getNormalizedNerSpan(LanguageInfo.java:130)
        at edu.stanford.nlp.sempre.NumberFn$1.check(NumberFn.java:81)
        at edu.stanford.nlp.sempre.NumberFn$1.createDerivation(NumberFn.java:45)
        at edu.stanford.nlp.sempre.SingleDerivationStream.hasNext(SingleDerivationStream.java:17)
        at edu.stanford.nlp.sempre.FloatingParserState.applyRuleActual(FloatingParser.java:239)
        at edu.stanford.nlp.sempre.FloatingParserState.applyRule(FloatingParser.java:206)
        at edu.stanford.nlp.sempre.FloatingParserState.applyFloatingRule(FloatingParser.java:261)
        at edu.stanford.nlp.sempre.FloatingParserState.buildFloating(FloatingParser.java:429)
        at edu.stanford.nlp.sempre.FloatingParserState.access$000(FloatingParser.java:154)
        at edu.stanford.nlp.sempre.FloatingParserState$1.run(FloatingParser.java:480)
        at java.lang.Thread.run(Thread.java:748)
 {
      Parser.ensureExecuted 
    }
  }
  Parser.setEvaluation: 0 candidates 
  Example: add 1 to 3 {
    Tokens: [add, 1, to, 3]
    Lemmatized tokens: [add, 1, to, 3]
    POS tags: [UNK, CD, UNK, CD]
    NER tags: [UNK, NUMBER, UNK, NUMBER]
    NER values: [UNK, 1, UNK, 3]
    Dependency children: []
  }

with the following grammar file nlp.grammar.simple:

(def @add edu.cmu.lia.semparse.TestFunctions.add)

(rule $NUM ($PHRASE) (NumberFn) )
(rule $ADD ($NUM $NUM)
        ( lambda x ( lambda y ( call @add ( var x ) ( var y ) ))) )
(rule $ROOT ($ADD) (IdentityFn))

and the following command-line:

java -cp libsempre/*:lib/*:out/production/sempre/edu/cmu/lia/semparse -ea edu.stanford.nlp.sempre.Main -Main.interactive -Grammar.inPaths instructable/nlp.grammar.simple -Builder.parser FloatingParser -useSizeInsteadOfDepth -FloatingParser.maxDepth 15

Am I missing something obvious?

**Comment by azimuthny** [comment]
Resolved by adding (anchored 1) to the (rule $NUM ($PHRASE) (NumberFn) ) rule
