### ISSUE TITLE
An error occurred when i was running " ./run @mode=tables @data=u-1 @feat=all @train=1 -maxExamples train:100 dev:100"

### ISSUE THREAD

**Issue by jingjingdd** [percyliang/sempre#210]
Exception in thread "main" java.lang.NumberFormatException: For input string: "tables.lambdadcs.LambdaDCSExecutor"
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 at java.lang.Integer.parseInt(Integer.java:580)
 at java.lang.Integer.parseInt(Integer.java:615)
 at fig.basic.OptInfo.interpretValue(OptionsParser.java:155)
 at fig.basic.OptInfo.set(OptionsParser.java:344)
 at fig.basic.OptionsParser.parse(OptionsParser.java:771)
 at fig.exec.Execution.init(Execution.java:212)
 at fig.exec.Execution.runWithObjArray(Execution.java:330)
 at fig.exec.Execution.run(Execution.java:325)
 at edu.stanford.nlp.sempre.Main.main(Main.java:50)

How can I solve the problem ？I look forward to hearing from you

**Comment by ppasupat** [comment]
The fig package currently breaks the run script. Please roll back as follows:
```
cd fig
git checkout d81d89d
```

**Comment by ppasupat** [comment]
#214 should now fix this. Please pull the latest code and try again.
