### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by ManasiPat** [percyliang/sempre#231]
I have all the necessary installation done. After running "ruby ./pull-dependencies core". Only fig folder is created no lib folder is created. 

![image](https://user-images.githubusercontent.com/44029189/186810179-21252046-6725-4d2b-8af9-e86c9224a4f6.png)

So when I try to run "ant core" Get the following error. Please suggest what is the issue.

Buildfile: C:\Users\1392287\Documents\sempre\build.xml

init:

BUILD FAILED
C:\Users\1392287\Documents\sempre\build.xml:18: Execute failed: java.io.IOException: Cannot run program ".\scripts\extract-module-classes.rb" (in directory "C:\Users\1392287\Documents\sempre"): CreateProcess error=193, %1 is not a valid Win32 application
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at java.base/java.lang.Runtime.exec(Runtime.java:615)
        at org.apache.tools.ant.taskdefs.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:424)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:438)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:660)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:699)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:527)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 23 more

Total time: 0 seconds

**Comment by ppasupat** [comment]
It looks like the Ruby script "extract-module-classes.rb" cannot be executed. Could you check if Ruby is installed? Maybe try changing [Line 18](https://github.com/percyliang/sempre/blob/master/build.xml#L18) in `build.xml` to
```
<exec executable="ruby"><arg value="${root}/scripts/extract-module-classes.rb"/></exec>
```

In general, SEMPRE was designed on Linux / Mac and might have issues when running on Windows. You could try emulating Linux using either [Cygwin](https://www.cygwin.com/) or a virtual machine.

**Comment by ManasiPat** [comment]
Thanks for the response. Ruby is installed. I made the suggested change, now the error is as follows: 
![image](https://user-images.githubusercontent.com/44029189/186821946-83329721-bab5-4e3e-a015-2969eb510af9.png)
After running "ruby ./pull-dependencies core". Only fig folder is created no lib folder is created.
![image](https://user-images.githubusercontent.com/44029189/186823230-2880fd2c-3859-41f7-89b7-500772c9f33d.png)

**Comment by ppasupat** [comment]
* Could you paste the content of `build.xml`? That error indicates an XML incorrect syntax.
* Could you try running `ruby ./scripts/extract-module-classes.rb`?

**Comment by ChiZhang-bit** [comment]
I also meet this problem. Do you solve?

**Comment by TomasaMuller** [comment]
I'm facing the same issue too. I was building with cygwin on Windows. 
I think the make step for "fig" is failing. I see that the classes folder is empty, so fig.jar cannot be generated.
I don't see any error's in the console in fact it says "BUILD SUCCESSFUL".
And due to the "exit 1" in the "pull dependencies" in the "fig" make cause the script to exit at that point.
