### ISSUE TITLE
Problems with Installation

### ISSUE THREAD

**Issue by atechnicolorskye** [percyliang/sempre#52]
Hi,

I'm hosting sempre on an EC2 instance and having followed the requirements and all the installation instructions, I'm stuck at ./run @mode=simple. 

I get this printout from the command:
/usr/local/bin/rlwrap
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: module-classes.txt (No such file or directory)
	at fig.basic.IOUtils.readLinesHard(IOUtils.java:479)
	at edu.stanford.nlp.sempre.Master.getOptionsParser(Master.java:412)
	at edu.stanford.nlp.sempre.Main.main(Main.java:38)
Caused by: java.io.FileNotFoundException: module-classes.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at fig.basic.IOUtils.openIn(IOUtils.java:121)
	at fig.basic.IOUtils.openIn(IOUtils.java:119)
	at fig.basic.IOUtils.readLines(IOUtils.java:398)
	at fig.basic.IOUtils.readLinesHard(IOUtils.java:478)
	... 2 more
Command failed: rlwrap java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -interactive

Thanks,
Sky

**Comment by percyliang** [comment]
Type:
make module-classes

**Comment by atechnicolorskye** [comment]
Hi Percy,

That worked, you might want to add it to the installation instructions. Thanks for the quick reply :)

Cheers,
Sky
