### ISSUE TITLE
missing in dependence (version 2.0)

### ISSUE THREAD

**Issue by JasonSmLing** [percyliang/sempre#54]
Hello 
I just started sempre 2.0,based of steps Easy Setup in readme file.
 > Picked up JAVA_TOOL_OPTIONS: -javaagent:/usr/share/java/jayatanaag.jar 
Exception in thread "main" java.lang.RuntimeException: java.io.FileNotFoundException: module-classes.txt (No such file or directory)
	at fig.basic.IOUtils.readLinesHard(IOUtils.java:479)
	at edu.stanford.nlp.sempre.Master.getOptionsParser(Master.java:412)
	at edu.stanford.nlp.sempre.Main.main(Main.java:38)
Caused by: java.io.FileNotFoundException: module-classes.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at fig.basic.IOUtils.openIn(IOUtils.java:121)
	at fig.basic.IOUtils.openIn(IOUtils.java:119)
	at fig.basic.IOUtils.readLines(IOUtils.java:398)
	at fig.basic.IOUtils.readLinesHard(IOUtils.java:478)
	... 2 more
Command failed: java -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -interactive

this error appears after
 * ./run @mode=simple

**Comment by percyliang** [comment]
type:
make module-classes
This will be fixed in the next release.

**Comment by JasonSmLing** [comment]
Thank you
