### ISSUE TITLE
Missing file: tutorial-freebase.lexicon

### ISSUE THREAD

**Issue by asher-stern** [percyliang/sempre#63]
According to the tutorial, I am running:
./run @mode=simple-freebase @sparqlserver=localhost:3001 -Grammar.inPaths freebase/data/tutorial-freebase.grammar -SimpleLexicon.inPaths freebase/data/tutorial-freebase.lexicon

I get an error message:

[asherst@skinsbegins sempre]$ ./run @mode=simple-freebase @sparqlserver=localhost:3001 -Grammar.inPaths freebase/data/tutorial-freebase.grammar -SimpleLexicon.inPaths freebase/data/tutorial-freebase.lexicon
/usr/local/bin/rlwrap
/usr/local/bin/rlwrap
main() {
  Grammar.read {
    SimpleLexicon.read(freebase/data/tutorial-freebase.lexicon)java.lang.RuntimeException: java.io.FileNotFoundException: freebase/data/tutorial-freebase.lexicon (No such file or directory)
	at edu.stanford.nlp.sempre.SimpleLexicon.read(SimpleLexicon.java:115)
	at edu.stanford.nlp.sempre.SimpleLexicon.<init>(SimpleLexicon.java:59)
	at edu.stanford.nlp.sempre.SimpleLexicon.getSingleton(SimpleLexicon.java:53)
	at edu.stanford.nlp.sempre.SimpleLexiconFn.<init>(SimpleLexiconFn.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at fig.basic.Utils.newInstanceHard(Utils.java:268)
	at edu.stanford.nlp.sempre.Grammar.parseSemanticFn(Grammar.java:467)
	at edu.stanford.nlp.sempre.Grammar.interpretRule(Grammar.java:255)
	at edu.stanford.nlp.sempre.Grammar.interpret(Grammar.java:154)
	at edu.stanford.nlp.sempre.Grammar.readOnePath(Grammar.java:130)
	at edu.stanford.nlp.sempre.Grammar.read(Grammar.java:61)
	at edu.stanford.nlp.sempre.Grammar.read(Grammar.java:53)
	at edu.stanford.nlp.sempre.Builder.buildUnspecified(Builder.java:45)
	at edu.stanford.nlp.sempre.Builder.build(Builder.java:38)
	at edu.stanford.nlp.sempre.Main.run(Main.java:17)
	at fig.exec.Execution.runWithObjArray(Execution.java:337)
	at fig.exec.Execution.run(Execution.java:325)
	at edu.stanford.nlp.sempre.Main.main(Main.java:38)
Caused by: java.io.FileNotFoundException: freebase/data/tutorial-freebase.lexicon (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at fig.basic.IOUtils.openIn(IOUtils.java:121)
	at fig.basic.IOUtils.openIn(IOUtils.java:119)
	at edu.stanford.nlp.sempre.SimpleLexicon.read(SimpleLexicon.java:68)
	... 21 more
 {
      ERROR: java.lang.RuntimeException: Error on (rule $Unary ($PHRASE) (SimpleLexiconFn (type fb:type.any))): java.lang.RuntimeException: java.io.FileNotFoundException: freebase/data/tutorial-freebase.lexicon (No such file or directory):
edu.stanford.nlp.sempre.Grammar.interpret(Grammar.java:176)
edu.stanford.nlp.sempre.Grammar.readOnePath(Grammar.java:130)
edu.stanford.nlp.sempre.Grammar.read(Grammar.java:61)
edu.stanford.nlp.sempre.Grammar.read(Grammar.java:53)
edu.stanford.nlp.sempre.Builder.buildUnspecified(Builder.java:45)
edu.stanford.nlp.sempre.Builder.build(Builder.java:38)
edu.stanford.nlp.sempre.Main.run(Main.java:17)
fig.exec.Execution.runWithObjArray(Execution.java:337)
fig.exec.Execution.run(Execution.java:325)
edu.stanford.nlp.sempre.Main.main(Main.java:38)
1 errors, 0 warnings
    }
Command failed: rlwrap java -Dmodules=core,freebase -cp libsempre/*:lib/* -ea edu.stanford.nlp.sempre.Main -executor freebase.SparqlExecutor -SparqlExecutor.endpointUrl http://localhost:3001/sparql -FreebaseSearch.cachePath FreebaseSearch.cache -EntityLexicon.mid2idPath freebase.cloudapp.net:4000:freebase-rdf-2013-06-09-00-00.canonical-id-map.gz -TypeInference.typeLookup freebase.FreebaseTypeLookup -FreebaseTypeLookup.entityTypesPath freebase.cloudapp.net:4000:freebase-rdf-2013-06-09-00-00.canonicalized.en-types.gz -EntityLexicon.maxEntries 2 -FeatureExtractor.featureDomains rule -Parser.coarsePrune -JoinFn.typeInference -UnaryLexicon.unaryLexiconFilePath /dev/null -BinaryLexicon.binaryLexiconFilesPath /dev/null -Grammar.inPaths freebase/data/demo1.grammar -SparqlExecutor.returnTable -Main.interactive -Grammar.inPaths freebase/data/tutorial-freebase.grammar -SimpleLexicon.inPaths freebase/data/tutorial-freebase.lexicon

**Comment by yonatansito** [comment]
Hi Asher (what's up?),
I added it to the repo.
Thanks!
Jonathan

**Comment by asher-stern** [comment]
Thanks.

**Comment by JilongZhang** [comment]
Hello：
       I want to ask some questions about CRF ，can you tell me your email，my email
is 644732913@qq.com thank you  very much.
